-- MySQL Script generated by MySQL Workbench
-- Πεμ 23 Μαΐ 2019 03:13:13 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publishers` (
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Date of Establishment` DATE NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Library` (
  `Library Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Library Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `ISBN` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Pages` INT NULL,
  `Publication Year` DATE NULL,
  `Publishers_Name` VARCHAR(45) NOT NULL,
  `Library_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Books_Publishers1_idx` (`Publishers_Name` ASC),
  INDEX `fk_Books_Library1_idx` (`Library_Name` ASC),
  CONSTRAINT `fk_Books_Publishers1`
    FOREIGN KEY (`Publishers_Name`)
    REFERENCES `mydb`.`Publishers` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_Library1`
    FOREIGN KEY (`Library_Name`)
    REFERENCES `mydb`.`Library` (`Library Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `AuthorID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Birthdate` DATE NULL,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Members` (
  `MemberID` INT NOT NULL,
  `Birthdate` DATE NULL,
  `Address` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Number of Books` INT NULL,
  `Can Borrow?` TINYINT(1) NULL,
  `Library_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MemberID`, `Library_Name`),
  INDEX `fk_Members_Library1_idx` (`Library_Name` ASC),
  CONSTRAINT `fk_Members_Library1`
    FOREIGN KEY (`Library_Name`)
    REFERENCES `mydb`.`Library` (`Library Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `StaffID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Pay` INT NULL,
  `Surname` VARCHAR(45) NULL,
  `Library_Name` INT NOT NULL,
  PRIMARY KEY (`StaffID`, `Library_Name`),
  INDEX `fk_Staff_Library_idx` (`Library_Name` ASC),
  CONSTRAINT `fk_Staff_Library`
    FOREIGN KEY (`Library_Name`)
    REFERENCES `mydb`.`Library` (`Library Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `Name` VARCHAR(45) NOT NULL,
  `Parent_category` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`),
  INDEX `fk_Category_Category1_idx` (`Parent_category` ASC),
  CONSTRAINT `fk_Category_Category1`
    FOREIGN KEY (`Parent_category`)
    REFERENCES `mydb`.`Category` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Copy` (
  `Number` INT NOT NULL,
  `Books_ISBN` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`, `Books_ISBN`),
  INDEX `fk_Copy_Books1_idx` (`Books_ISBN` ASC),
  CONSTRAINT `fk_Copy_Books1`
    FOREIGN KEY (`Books_ISBN`)
    REFERENCES `mydb`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temporary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temporary` (
  `Staff_StaffID` INT NOT NULL,
  `ContractID` INT NOT NULL,
  PRIMARY KEY (`Staff_StaffID`),
  INDEX `fk_Temporary_Staff1_idx` (`Staff_StaffID` ASC),
  CONSTRAINT `fk_Temporary_Staff1`
    FOREIGN KEY (`Staff_StaffID`)
    REFERENCES `mydb`.`Staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permanent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permanent` (
  `Staff_StaffID` INT NOT NULL,
  `HIring Date` DATE NOT NULL,
  PRIMARY KEY (`Staff_StaffID`),
  INDEX `fk_Permanent_Staff1_idx` (`Staff_StaffID` ASC),
  CONSTRAINT `fk_Permanent_Staff1`
    FOREIGN KEY (`Staff_StaffID`)
    REFERENCES `mydb`.`Staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Borrows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Borrows` (
  `Members_MemberID` INT NOT NULL,
  `Copy_Number` INT NOT NULL,
  `Copy_Books_ISBN` VARCHAR(45) NOT NULL,
  `Start Date` DATE NULL,
  `Return date` DATE NULL,
  `Due Date` DATE NULL,
  PRIMARY KEY (`Members_MemberID`, `Copy_Number`, `Copy_Books_ISBN`),
  INDEX `fk_Members_has_Copy_Copy1_idx` (`Copy_Number` ASC, `Copy_Books_ISBN` ASC),
  INDEX `fk_Members_has_Copy_Members1_idx` (`Members_MemberID` ASC),
  CONSTRAINT `fk_Members_has_Copy_Members1`
    FOREIGN KEY (`Members_MemberID`)
    REFERENCES `mydb`.`Members` (`MemberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Members_has_Copy_Copy1`
    FOREIGN KEY (`Copy_Number` , `Copy_Books_ISBN`)
    REFERENCES `mydb`.`Copy` (`Number` , `Books_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Belongs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Belongs` (
  `Books_ISBN` VARCHAR(45) NOT NULL,
  `Category_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Books_ISBN`, `Category_Name`),
  INDEX `fk_Books_has_Category_Category1_idx` (`Category_Name` ASC),
  INDEX `fk_Books_has_Category_Books1_idx` (`Books_ISBN` ASC),
  CONSTRAINT `fk_Books_has_Category_Books1`
    FOREIGN KEY (`Books_ISBN`)
    REFERENCES `mydb`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_has_Category_Category1`
    FOREIGN KEY (`Category_Name`)
    REFERENCES `mydb`.`Category` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authored`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authored` (
  `Authors_AuthorID` INT NOT NULL,
  `Books_ISBN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Authors_AuthorID`, `Books_ISBN`),
  INDEX `fk_Authors_has_Books_Books1_idx` (`Books_ISBN` ASC),
  INDEX `fk_Authors_has_Books_Συγγραφεί_idx` (`Authors_AuthorID` ASC),
  CONSTRAINT `fk_Authors_has_Books_Authors1`
    FOREIGN KEY (`Authors_AuthorID`)
    REFERENCES `mydb`.`Authors` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Authors_has_Books_Books1`
    FOREIGN KEY (`Books_ISBN`)
    REFERENCES `mydb`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reminds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reminds` (
  `Staff_StaffID` INT NOT NULL,
  `Members_MemberID` INT NOT NULL,
  `Date of Reminder` DATE NULL,
  PRIMARY KEY (`Staff_StaffID`, `Members_MemberID`),
  INDEX `fk_Staff_has_Members_Members1_idx` (`Members_MemberID` ASC),
  INDEX `fk_Staff_has_Members_Worker_idx` (`Staff_StaffID` ASC),
  CONSTRAINT `fk_Staff_has_Members_Staff1`
    FOREIGN KEY (`Staff_StaffID`)
    REFERENCES `mydb`.`Staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_has_Members_Members1`
    FOREIGN KEY (`Members_MemberID`)
    REFERENCES `mydb`.`Members` (`MemberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
